boards:
  - name: planck_left
    vendor: yangxing
    socs:
      - name: nrf52840
        variants:
          - name: zmk
  - name: planck_right
    vendor: yangxing
    socs:
      - name: nrf52840
        variants:
          - name: zmk
