# SPDX-License-Identifier: MIT

# 五个蓝牙配置文件及右半外设连接。
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# 左半是唯一的 USB 和 HID 输出端。
CONFIG_ZMK_USB=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
